-- Enable required extensions
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  internal_id bigint generated by default as identity,
  vertical text,
  provider_type text check (provider_type in ('provider','direct_merchant','aggregator_provider','aggregator_merchant')),
  stake numeric,
  cheki numeric,
  rolling_reserve boolean default false,
  insurance boolean default false,
  settlement text,
  date date
);

alter table public.offers enable row level security;

-- Allow everything for anon (app enforces password on client)
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='offers' and policyname='offers_select_all') then
    create policy offers_select_all on public.offers for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='offers' and policyname='offers_insert_all') then
    create policy offers_insert_all on public.offers for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='offers' and policyname='offers_update_all') then
    create policy offers_update_all on public.offers for update using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='offers' and policyname='offers_delete_all') then
    create policy offers_delete_all on public.offers for delete using (true);
  end if;
end$$;
